### ISSUE TITLE
Step 6.2 - Error during sam build -  RuntimeError: Container does not exist. Cannot get logs for this container [31060] Failed to execute script __main__

### ISSUE THREAD

**Issue by fernandomullerjr** [aws-samples/aws-serverless-tokenization#2]
Hello,
i was with this error during the build of SAM template:

```bash
fernando.junior:~/environment/aws-serverless-tokenization/src/tokenizer (master) $ 
fernando.junior:~/environment/aws-serverless-tokenization/src/tokenizer (master) $ cd ../../../aws-serverless-tokenization/src/CustomerApp/
fernando.junior:~/environment/aws-serverless-tokenization/src/CustomerApp (master) $ sam build --use-container --parameter-overrides layerarn=arn:aws:lambda:us-east-2:814635504079:layer:TokenizeData:1
Starting Build inside a container
Building codeuri: /home/ec2-user/environment/aws-serverless-tokenization/src/CustomerApp/payment_method runtime: python3.7 metadata: {} architecture: x86_64 functions: CustomerOrderFunction

Fetching public.ecr.aws/sam/build-python3.7:latest-x86_64 Docker container image.............................................................................................................................................................................................................................................................................................
Mounting /home/ec2-user/environment/aws-serverless-tokenization/src/CustomerApp/payment_method as /tmp/samcli/source:ro,delegated inside runtime container
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 176, in wrapped
  File "samcli/lib/telemetry/metric.py", line 126, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 86, in wrapper
  File "samcli/commands/build/command.py", line 196, in cli
  File "samcli/commands/build/command.py", line 257, in do_cli
  File "samcli/commands/build/build_context.py", line 252, in run
  File "samcli/lib/build/app_builder.py", line 221, in build
  File "samcli/lib/build/build_strategy.py", line 80, in build
  File "samcli/lib/build/build_strategy.py", line 90, in _build_functions
  File "samcli/lib/build/build_strategy.py", line 174, in build_single_function_definition
  File "samcli/lib/build/app_builder.py", line 654, in _build_function
  File "samcli/lib/build/app_builder.py", line 831, in _build_function_on_container
  File "samcli/local/docker/container.py", line 328, in wait_for_logs
RuntimeError: Container does not exist. Cannot get logs for this container
[31060] Failed to execute script __main__
fernando.junior:~/environment/aws-serverless-tokenization/src/CustomerApp (master) $ 
```

The solution for me was resize the EBS volume of Cloud9 instance.

Cloud9 may have a problem with the storage space. 
It's a good idea to prepull image manually - e.g. docker pull public.ecr.aws/sam/build-python3.7:latest-x86_64
e.g. docker pull lambci/lambda:build-python3.7
To see if image is pulled and extraced successfully or if docker pull finishes with no space left on device error (unfortunaly sam build doesn't show this error in Fetching <image> Docker container image output). 
If there is a problem with the space, then some unused docker images may be deleted.

**Comment by amrih-pg** [comment]
I had this issue as well. Extending the EBS volume does seems to fix this particular issue

**Comment by anujag24** [comment]
Thanks for your feedback. We have recently released a new version of the code that won't require you to use Cloud9 instance.
